name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: latest
      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: latest

      - name: Install
        run: pnpm install

      - name: Test
        run: pnpm run test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: latest
      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: latest

      - name: Install
        run: pnpm install

      - name: Coverage
        run: pnpm run coverage
